# Generated by Django 5.0.3 on 2024-03-09 16:43

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
import django.db.models.deletion
import job.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200, null=True)),
                ('salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('position', models.IntegerField(default=1)),
                ('company', models.CharField(max_length=100, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326)),
                ('lastDate', models.DateTimeField(default=job.models.return_default_date)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jobType', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Temporary', 'Temporary')], default='Permanent', max_length=100)),
                ('education', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'Phd')], default='Bachelor', max_length=100)),
                ('industry', models.CharField(choices=[('IT', 'It'), ('Business', 'Business'), ('Banking', 'Banking'), ('Education', 'Education'), ('Telecommunication', 'Telecommunication'), ('Others', 'Others')], default='Others', max_length=100)),
                ('experience', models.CharField(choices=[('No Experience', 'No Experience'), ('1 Year', 'One Year'), ('2 Years', 'Two Years'), ('3 Years', 'Three Years')], default='No Experience', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
